baseURL = "https://krissh-wtf.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "krissh"

enableRobotsTXT = true
copyright = "krissh.wtf"

[module]
  [[module.imports]]
    path = 'github.com/clente/hugo-bearcub'

[languages]
[languages.en]
languageName = "🇬🇧"
LanguageCode = "en-US"
contentDir = "content"
[languages.en.params]
madeWith = "made with [bear cub](https://github.com/clente/hugo-bearcub)"

[languages.fr]
languageName = "🇫🇷"
LanguageCode = "fr-FR"
contentDir = "content.fr"
[languages.fr.params]
madeWith = "fait avec [bear cub](https://github.com/clente/hugo-bearcub)"

[params]
description = "my personal website"
favicon = "favicon.svg"
dateFormat = "02/01/2006"
themeStyle = "herman"
generateSocialCard = false

[params.author]
name = "krissh sivaparan"
emaim = "moi@krissh.wtf"
